apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-config
  namespace: kube-monitor
data:
  prometheus.yaml: |-
    {
        "apiVersion": 1,
        "datasources": [
            {
               "access":"proxy",
                "editable": true,
                "name": "prometheus",
                "orgId": 1,
                "type": "prometheus",
                "url": "http://prometheus-service.kube-monitor.svc:8080",
                "version": 1
            }
        ]
    }
